// This file is generated by scripts/codegen/generate-api-client.mjs.
// Do not edit by hand.

export type HttpMethod = "DELETE" | "GET" | "PATCH" | "POST" | "PUT";

export type ApiOperation = {
  method: HttpMethod;
  path: string;
  operationId: string;
  tags: readonly string[];
};

export const operations = [
  {
    "method": "DELETE",
    "path": "/v1/me/account",
    "operationId": "delete_v1_me_account",
    "tags": [
      "me"
    ]
  },
  {
    "method": "DELETE",
    "path": "/v1/me/sessions/{id}",
    "operationId": "delete_v1_me_sessions_by_id",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/auth/me",
    "operationId": "get_v1_auth_me",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/bookings",
    "operationId": "get_v1_bookings",
    "tags": [
      "marketplace",
      "bookings"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/bookings/{id}",
    "operationId": "get_v1_bookings_by_id",
    "tags": [
      "marketplace",
      "bookings"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/complaints/{id}",
    "operationId": "get_v1_complaints_by_id",
    "tags": [
      "complaints"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/evidence/{booking_id}",
    "operationId": "get_v1_evidence_by_booking_id",
    "tags": [
      "evidence"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/bookings",
    "operationId": "get_v1_me_bookings",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/data-export/{job_id}",
    "operationId": "get_v1_me_data_export_by_job_id",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/notifications/preferences",
    "operationId": "get_v1_me_notifications_preferences",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/profile",
    "operationId": "get_v1_me_profile",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/sessions",
    "operationId": "get_v1_me_sessions",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/me/vehicles",
    "operationId": "get_v1_me_vehicles",
    "tags": [
      "me"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchant-services/{id}/price-history",
    "operationId": "get_v1_merchant_services_by_id_price_history",
    "tags": [
      "merchant-services"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}",
    "operationId": "get_v1_merchants_by_id",
    "tags": [
      "marketplace",
      "merchants"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/bays",
    "operationId": "get_v1_merchants_by_id_bays",
    "tags": [
      "marketplace",
      "merchants"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/calendar",
    "operationId": "get_v1_merchants_by_id_calendar",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/daily-summary",
    "operationId": "get_v1_merchants_by_id_daily_summary",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/daily-summary.csv",
    "operationId": "get_v1_merchants_by_id_daily_summary_csv",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/ekyc/status",
    "operationId": "get_v1_merchants_by_id_ekyc_status",
    "tags": [
      "merchant-ekyc"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/golden-hour",
    "operationId": "get_v1_merchants_by_id_golden_hour",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/queue",
    "operationId": "get_v1_merchants_by_id_queue",
    "tags": [
      "marketplace",
      "merchant"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/{id}/services",
    "operationId": "get_v1_merchants_by_id_services",
    "tags": [
      "marketplace",
      "merchants"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/merchants/nearby",
    "operationId": "get_v1_merchants_nearby",
    "tags": [
      "marketplace",
      "merchants"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/audit-log",
    "operationId": "get_v1_ops_audit_log",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/commission-receivables",
    "operationId": "get_v1_ops_commission_receivables",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/complaints",
    "operationId": "get_v1_ops_complaints",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/data-room/{section}",
    "operationId": "get_v1_ops_data_room_by_section",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/exports/{job_id}",
    "operationId": "get_v1_ops_exports_by_job_id",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/merchants/pending",
    "operationId": "get_v1_ops_merchants_pending",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/ops/users",
    "operationId": "get_v1_ops_users",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/payments/{id}",
    "operationId": "get_v1_payments_by_id",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/promo-codes/user",
    "operationId": "get_v1_promo_codes_user",
    "tags": [
      "promo"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/referrals/me",
    "operationId": "get_v1_referrals_me",
    "tags": [
      "referrals"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/rewards/progress",
    "operationId": "get_v1_rewards_progress",
    "tags": [
      "rewards"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/rewards/vouchers",
    "operationId": "get_v1_rewards_vouchers",
    "tags": [
      "rewards"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/search",
    "operationId": "get_v1_search",
    "tags": [
      "marketplace",
      "search"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/service-templates",
    "operationId": "get_v1_service_templates",
    "tags": [
      "marketplace",
      "search"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/flags",
    "operationId": "getFlags",
    "tags": [
      "platform"
    ]
  },
  {
    "method": "GET",
    "path": "/healthz",
    "operationId": "getHealthz",
    "tags": [
      "platform"
    ]
  },
  {
    "method": "GET",
    "path": "/metrics",
    "operationId": "getMetrics",
    "tags": [
      "platform"
    ]
  },
  {
    "method": "GET",
    "path": "/readyz",
    "operationId": "getReadyz",
    "tags": [
      "platform"
    ]
  },
  {
    "method": "GET",
    "path": "/v1/app/version-check",
    "operationId": "getVersionCheck",
    "tags": [
      "platform"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/me/notifications/preferences",
    "operationId": "patch_v1_me_notifications_preferences",
    "tags": [
      "me"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/me/profile",
    "operationId": "patch_v1_me_profile",
    "tags": [
      "me"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/me/vehicles/{id}",
    "operationId": "patch_v1_me_vehicles_by_id",
    "tags": [
      "me"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/merchant-services/{id}",
    "operationId": "patch_v1_merchant_services_by_id",
    "tags": [
      "merchant-services"
    ]
  },
  {
    "method": "PATCH",
    "path": "/v1/ops/complaints/{id}",
    "operationId": "patch_v1_ops_complaints_by_id",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/exists",
    "operationId": "post_v1_auth_exists",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/forgot-password",
    "operationId": "post_v1_auth_forgot_password",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/login",
    "operationId": "post_v1_auth_login",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/logout",
    "operationId": "post_v1_auth_logout",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/logout-all",
    "operationId": "post_v1_auth_logout_all",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/refresh",
    "operationId": "post_v1_auth_refresh",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/auth/signup",
    "operationId": "post_v1_auth_signup",
    "tags": [
      "auth"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/arrived",
    "operationId": "post_v1_bookings_by_id_arrived",
    "tags": [
      "bookings"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/cancel",
    "operationId": "post_v1_bookings_by_id_cancel",
    "tags": [
      "marketplace",
      "bookings"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/check-in",
    "operationId": "post_v1_bookings_by_id_check_in",
    "tags": [
      "marketplace",
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/complete-service",
    "operationId": "post_v1_bookings_by_id_complete_service",
    "tags": [
      "marketplace",
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/rate",
    "operationId": "post_v1_bookings_by_id_rate",
    "tags": [
      "bookings"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/{id}/start-service",
    "operationId": "post_v1_bookings_by_id_start_service",
    "tags": [
      "marketplace",
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/bookings/holds",
    "operationId": "post_v1_bookings_holds",
    "tags": [
      "marketplace",
      "bookings"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/complaints",
    "operationId": "post_v1_complaints",
    "tags": [
      "complaints"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/evidence/{booking_id}/presign",
    "operationId": "post_v1_evidence_by_booking_id_presign",
    "tags": [
      "evidence"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/evidence/{evidence_id}/confirm",
    "operationId": "post_v1_evidence_by_evidence_id_confirm",
    "tags": [
      "evidence"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/cancel-delete",
    "operationId": "post_v1_me_cancel_delete",
    "tags": [
      "me"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/data-export",
    "operationId": "post_v1_me_data_export",
    "tags": [
      "me"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/notifications/register",
    "operationId": "post_v1_me_notifications_register",
    "tags": [
      "me"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/password",
    "operationId": "post_v1_me_password",
    "tags": [
      "me"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/me/vehicles",
    "operationId": "post_v1_me_vehicles",
    "tags": [
      "me"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchant-services",
    "operationId": "post_v1_merchant_services",
    "tags": [
      "merchant-services"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchant-services/{id}/resubmit",
    "operationId": "post_v1_merchant_services_by_id_resubmit",
    "tags": [
      "merchant-services"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchant-services/custom",
    "operationId": "post_v1_merchant_services_custom",
    "tags": [
      "merchant-services"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/applications",
    "operationId": "post_v1_merchants_applications",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/calendar/maintenance",
    "operationId": "post_v1_merchants_by_id_calendar_maintenance",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/confirm-photo",
    "operationId": "post_v1_merchants_by_id_confirm_photo",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/ekyc/bank",
    "operationId": "post_v1_merchants_by_id_ekyc_bank",
    "tags": [
      "merchant-ekyc"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/ekyc/cmnd",
    "operationId": "post_v1_merchants_by_id_ekyc_cmnd",
    "tags": [
      "merchant-ekyc"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/ekyc/selfie",
    "operationId": "post_v1_merchants_by_id_ekyc_selfie",
    "tags": [
      "merchant-ekyc"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/merchants/{id}/payment-setup",
    "operationId": "post_v1_merchants_by_id_payment_setup",
    "tags": [
      "merchant"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/bookings",
    "operationId": "post_v1_ops_bookings",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/bookings/{id}/check-in",
    "operationId": "post_v1_ops_bookings_by_id_check_in",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/evidence/upload",
    "operationId": "post_v1_ops_evidence_upload",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/exports",
    "operationId": "post_v1_ops_exports",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchant-services/{id}/approve",
    "operationId": "post_v1_ops_merchant_services_by_id_approve",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchant-services/{id}/reject",
    "operationId": "post_v1_ops_merchant_services_by_id_reject",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchants/{id}/approve",
    "operationId": "post_v1_ops_merchants_by_id_approve",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchants/{id}/reject",
    "operationId": "post_v1_ops_merchants_by_id_reject",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchants/{id}/suspend",
    "operationId": "post_v1_ops_merchants_by_id_suspend",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/merchants/{id}/verify-payment-recipient",
    "operationId": "post_v1_ops_merchants_by_id_verify_payment_recipient",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/payments/{id}/confirm",
    "operationId": "post_v1_ops_payments_by_id_confirm",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/promo-codes",
    "operationId": "post_v1_ops_promo_codes",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/reward/voucher",
    "operationId": "post_v1_ops_reward_voucher",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/users",
    "operationId": "post_v1_ops_users",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/ops/users/{id}/reset-password",
    "operationId": "post_v1_ops_users_by_id_reset_password",
    "tags": [
      "ops"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/{id}/cash-record",
    "operationId": "post_v1_payments_by_id_cash_record",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/{id}/merchant-confirmed",
    "operationId": "post_v1_payments_by_id_merchant_confirmed",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/{id}/merchant-denied",
    "operationId": "post_v1_payments_by_id_merchant_denied",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/{id}/switch-method",
    "operationId": "post_v1_payments_by_id_switch_method",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/{id}/user-claimed",
    "operationId": "post_v1_payments_by_id_user_claimed",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/payments/initiate",
    "operationId": "post_v1_payments_initiate",
    "tags": [
      "payments"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/promo-codes/validate",
    "operationId": "post_v1_promo_codes_validate",
    "tags": [
      "promo"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/realtime/token",
    "operationId": "post_v1_realtime_token",
    "tags": [
      "realtime"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/referrals/share-event",
    "operationId": "post_v1_referrals_share_event",
    "tags": [
      "referrals"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/rewards/vouchers/{id}/redeem",
    "operationId": "post_v1_rewards_vouchers_by_id_redeem",
    "tags": [
      "rewards"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/rewards/vouchers/{id}/release",
    "operationId": "post_v1_rewards_vouchers_by_id_release",
    "tags": [
      "rewards"
    ]
  },
  {
    "method": "POST",
    "path": "/v1/rewards/vouchers/{id}/reserve",
    "operationId": "post_v1_rewards_vouchers_by_id_reserve",
    "tags": [
      "rewards"
    ]
  },
  {
    "method": "PUT",
    "path": "/v1/merchants/{id}/golden-hour",
    "operationId": "put_v1_merchants_by_id_golden_hour",
    "tags": [
      "merchant"
    ]
  }
] as const satisfies readonly ApiOperation[];

export type ApiClientOptions = {
  baseUrl: string;
  fetchImpl?: typeof fetch;
  headers?: Record<string, string>;
};

export function createApiClient(options: ApiClientOptions) {
  const fetcher = options.fetchImpl ?? fetch;

  return {
    operations,

    async request<T>(method: HttpMethod, path: string, body?: unknown): Promise<T> {
      const response = await fetcher(new URL(path, options.baseUrl), {
        method,
        headers: {
          "content-type": "application/json",
          ...options.headers
        },
        body: body === undefined ? undefined : JSON.stringify(body)
      });

      if (!response.ok) {
        throw await response.json();
      }

      const text = await response.text();
      return (text ? JSON.parse(text) : undefined) as T;
    }
  };
}
